### ISSUE TITLE
功能特性建议

### ISSUE THREAD

**Issue by AceAmy** [Nevolution/decorator-wechat#1]
要是有已读或者已回复则自动消失对应通知，以及打开微信的某个对话则自动消失对应通知的特性，就更人性化了。不然经常要手动清除怪麻烦的hhh。
希望feng大佬加入此特性吖:relaxed:

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 OnePlus5 发送_

**Comment by oasisfeng** [comment]
这依赖于 Nevolution 引擎部分的一个重大调整。计划在近期进行试验。

**Comment by AceAmy** [comment]
我要继续内测！
2333
大佬加油！

From 鸣锴的Gmail For Android

oasisfeng <notifications@github.com> 于 2018年7月2日周一 上午12:57写道：

**Comment by lzyang2000** [comment]
所以这个功能3.0版本是完成了吗？如果是的话，那我的手机就出bug了 TAT

**Comment by oasisfeng** [comment]
> 所以这个功能3.0版本是完成了吗？如果是的话，那我的手机就出bug了 TAT

需要开启 3.0 设置中的 Insider 模式。

**Comment by lzyang2000** [comment]
嗯，重装就好了。。看来是有bug，复现的时候我看看能不能抓log
