### ISSUE TITLE
decorator-wechat用的是哪个IDE的源代码布局？

### ISSUE THREAD

**Issue by notxx** [Nevolution/decorator-wechat#10]
打算分叉一下把群ID有emoji和群友ID有unicode粗体/斜体的问题修一下，不过用Android Studio直接改好像布局完全乱了，修好了也不方便合并。我应该用什么呢？

**Comment by oasisfeng** [comment]
不是很理解「源代码布局」是什么，与具体的代码实现有什么联系？

**Comment by notxx** [comment]
就是当我把源代码导入Android Studio的时候，需要把很多现有文件移动位置还有增加一堆配置文件。
不过现在的源代码是直接用gradle编译的是吗？我来用这个
