### ISSUE TITLE
Android P 头像问题

### ISSUE THREAD

**Issue by Rick0525** [Nevolution/decorator-wechat#12]
小米6 开发版 9.5.30 Android P
Magisk的su 内源模式
回微信后头像不显示

**Comment by Rick0525** [comment]
哦对 2.1版本

**Comment by oasisfeng** [comment]
回复的本人头像使用的是你在通讯录中个人资料（profile）里设置的头像。

**Comment by notxx** [comment]
MIUI上如果开了MIUI优化，个人资料的头像就没了……
