### ISSUE TITLE
微信来消息会有双通知的感觉。

### ISSUE THREAD

**Issue by windylike** [Nevolution/decorator-wechat#2]
微信来消息会先弹系统的通知，然后才有nevolution的通知，应该怎么解决？冯大。

**Comment by oasisfeng** [comment]
反馈问题请首先注明机型、ROM、Android 版本。

**Comment by windylike** [comment]
抱歉，疏忽了，我以为是每部都会有，LG g5，LG自带系统，Android 7.0

**Comment by oasisfeng** [comment]
@honponkon 目前还在小范围测试阶段，暂时不提供开放的下载地址。

**Comment by honponkon** [comment]
@oasisfeng 了解，谢谢。期待正式上线！
