### ISSUE TITLE
用nevo的adb指令开启通知同步移除，只能够对微信起作用

### ISSUE THREAD

**Issue by shihuajie1998** [Nevolution/decorator-wechat#20]
用nevo的adb指令开启通知同步移除，只能够对微信起作用，对于其他应用，无法在点开应用的时候同步移除相应的通知，比较麻烦。

**Comment by oasisfeng** [comment]
如果应用原本就不会主动移除通知，开启这个特性 Nevolution 也不会越俎代庖。

PS，这里只接受微信插件的相关问题反馈。
