### ISSUE TITLE
刮掉微信企业号消息通知无法标记已读

### ISSUE THREAD

**Issue by yuhangrao** [Nevolution/decorator-wechat#21]
开启扩展功能后划掉通知正常消息可以标记已读，但是企业微信号的消息无法标记已读

**Comment by oasisfeng** [comment]
你指的是微信公众号，还是企业微信账号发来的消息？

**Comment by by-love** [comment]
> 你指的是微信公众号，还是企业微信账号发来的消息？

企业微信账号发来的消息

**Comment by oasisfeng** [comment]
无法重现这个问题。你确定说的是「企业微信」( https://work.weixin.qq.com/ )？

**Comment by by-love** [comment]
> 无法重现这个问题。你确定说的是「企业微信」( https://work.weixin.qq.com/ )？

是企业微信号发来的消息（也许应该这么说），图中那样的。用的是普通微信不是企业微信版本，也不是公众号，普通关注的公众号推送的消息不会有通知。
![Screenshot_20191217-011255](https://user-images.githubusercontent.com/28585220/70928270-a16baf80-206b-11ea-9ad8-65348b3ad1e4.png)
![Screenshot_20191217-011720](https://user-images.githubusercontent.com/28585220/70928275-a466a000-206b-11ea-91bc-fe1e8c02e6d7.png)
![Uploading Screenshot_20191217-011349.png…]()

**Comment by by-love** [comment]
> 无法重现这个问题。你确定说的是「企业微信」( https://work.weixin.qq.com/ )？
> 
> 是企业微信号发来的消息（也许应该这么说），图中那样的。用的是普通微信不是企业微信版本，也不是公众号，普通关注的公众号推送的消息不会有通知。

上传失败的截图
![Screenshot_20191217-011349](https://user-images.githubusercontent.com/28585220/70928430-ff989280-206b-11ea-8d81-0fa76e8a7b43.png)

**Comment by oasisfeng** [comment]
你说的这种消息，我这边似乎很难有条件进行测试……？

**Comment by by-love** [comment]
> 你说的这种消息，我这边似乎很难有条件进行测试……？

...下次复现我会提供截图，测试的话，这个不需要身份验证，关注就可以收到消息，可以关注测试一下，但是不确定什么时候收到消息...
https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzIzODEwNTAzMQ==#wechat_redirect

**Comment by by-love** [comment]
> 你说的这种消息，我这边似乎很难有条件进行测试……？

复现截图，未标记已读
![Screenshot_20191219-122528~2](https://user-images.githubusercontent.com/28585220/71170509-68fbe980-2296-11ea-995f-432ebed76226.png)
![Screenshot_20191219-122543~2](https://user-images.githubusercontent.com/28585220/71170528-75804200-2296-11ea-8f1a-c0bb7e7f5e8d.png)
