### ISSUE TITLE
优化后的通话通知问题

### ISSUE THREAD

**Issue by SingSky** [Nevolution/decorator-wechat#22]
优化后的通话通知在以下情况下出现问题：
1. 对方发起微信通话，本机未接的情况下，这条通知持续出现，不可移除（即使已经向右划出了微信原本的通话通知），需要手动在通知类型管理里临时取消权限才能消除，或者直接点击通知来消除（但是这一行为会向对方发起通话）

2.在通话结束后，有一定几率通知不会消失并持续计时，表现同上。

本机：Samsung Galaxy S9+
系统环境：Android 9.0，One UI 1.0（Official）

**Comment by oasisfeng** [comment]
这个特性将在下个版本中暂时移除，后续将以新的方式实现。
