### ISSUE TITLE
直接回复功能支持 Android 7.0吗？

### ISSUE THREAD

**Issue by lidg888** [Nevolution/decorator-wechat#23]
直接回复功能支持 Android 7.0吗？

**Comment by oasisfeng** [comment]
支持

**Comment by lidg888** [comment]
> 支持（部分国产系统除外）

 我的手机是MIUI Android 7.0 女娲石和扩展权限全开（包括通知和悬浮窗），可以接收到微信通知，但通知栏没有 回复？

**Comment by lidg888** [comment]
> 支持（部分国产系统除外）

MIUI是不支持的？

**Comment by oasisfeng** [comment]
> > 支持（部分国产系统除外）
> 
> MIUI是不支持的？

MIUI 的 Android 7 系统中，SystemUI 部分用的是旧版本 Android 的，所以无法支持。

**Comment by lidg888** [comment]
> > MIUI是不支持的？
> 
> MIUI 的 Android 7 系统中，SystemUI 部分用的是旧版本 Android 的，所以无法支持。

了解，谢谢！
