### ISSUE TITLE
时常无法替换微信自身通知

### ISSUE THREAD

**Issue by Racham** [Nevolution/decorator-wechat#24]
经常无法替换微信自身的通知方式
有微信消息的时候是微信本身的通知框弹出

Google Pixel 4 XL
January Original Android 10
Magisk Root
Wechat 7.0.9 from Google Play Store

内源模式已开启

未安装Extension Park和女娲石•即时通讯增强

另：之前同时安装过Extension Park和微信即时通讯增强，但一段时间后，通讯增强app的启用状态会失效，点击启用后会弹出激活选择提示框，但之前是激活过的，遂目前是卸载了这两个应用只保留女娲石主体

**Comment by Racham** [comment]
昨晚装上extension park后，单聊会使用代理通知，群聊不会，但群聊里的消息撤回通知会使用代理通知

**Comment by oasisfeng** [comment]
最新版本应该已经修复了上述问题，请确认。

**Comment by Racham** [comment]
通过Google Play Store加入Beta版更新女娲石到1月2日的5.6.5版本后，使用几天下来，微信的群通知可以被正常代理，没有出现未被替换的情况，感谢！
