### ISSUE TITLE
[问题]无法授予通知使用权限

### ISSUE THREAD

**Issue by Neubulae** [Nevolution/decorator-wechat#25]
![Screenshot_20200320-164505_](https://user-images.githubusercontent.com/24774842/77148765-259a5c80-6acb-11ea-92aa-089d021e3d8c.png)
这是咋…

**Comment by notxx** [comment]
这是哪个魔改系统吗？安利一下我为了在魔改系统用decorator-wechat做的项目
https://github.com/notxx/NevolutionXposed/releases

**Comment by oasisfeng** [comment]
如果你的系统是 Android Go，或者 ROM 启用了「低内存容量」的优化开关，就会禁用这个机制，你就会看到图中的提示。

@notxx 这是 AOSP 本身的机制

**Comment by Neubulae** [comment]
> 如果你的系统是 Android Go，或者 ROM 启用了「低内存容量」的优化开关，就会禁用女娲石所依赖的这个「通知使用权」机制，你就会看到图中的提示。
> 
> 这个情况目前无解，除非刷别的 ROM。
> 
> @notxx 这是 AOSP 本身的机制

明白，我这就关

**Comment by Neubulae** [comment]
奇怪，咋关不掉了，那看来还是ROM的问题
还是感谢帮助

**Comment by oasisfeng** [comment]
> 奇怪，咋关不掉了，那看来还是ROM的问题

那是 ROM 编译时的开关，用户是无法关闭的。

**Comment by Neubulae** [comment]
> > 奇怪，咋关不掉了，那看来还是ROM的问题
> 
> 那是 ROM 编译时的开关，用户是无法关闭的。

谷歌了一下说是build.prop里面加一句就可以，看来是我多氯了
