### ISSUE TITLE
一加3T 氧os 8.0系统用电脑登陆微信，手机收到消息还会有提示

### ISSUE THREAD

**Issue by seraph758** [Nevolution/decorator-wechat#3]
已经在手机的微信上开启了消息静音，收到消息后还会有系统提示和这个app的提示 以前没安装的时候手机上开启消息静音就只有电脑上提示消息

**Comment by oasisfeng** [comment]
的确会有这个问题，谢谢反馈。

**Comment by oasisfeng** [comment]
微信升级至 7.0 后，这个问题应该已不复存在。还请确认，谢谢！

**Comment by seraph758** [comment]
> 微信升级至 7.0 后，这个问题应该已不复存在。还请确认，谢谢！

用这个用的少，所以不知道确认应该怎么操作。。。。麻烦跟我说一下吧
