### ISSUE TITLE
Compatibility mode brings Google maps in drive mode

### ISSUE THREAD

**Issue by HankAviator** [Nevolution/decorator-wechat#39]
After enabling "compatibility mode" Google maps no longer shows up as normal interface but optimised for driving.
Related: #35

**Comment by cherryleafroad** [comment]
I disabled the Android auto app to solve the issue in #35, and my maps has no issue. Does that work for you too?

**Comment by HankAviator** [comment]
@cherryleafroad yes but as you said, after a reboot Nevolution won't work as intended.

**Comment by cherryleafroad** [comment]
I used tasker to solve that by making an api call to enable car mode at boot
