### ISSUE TITLE
希望可在提醒设置中设置nevo-WeChat的通知提醒，完全接管WeChat的消息提醒

### ISSUE THREAD

**Issue by wolf3c** [Nevolution/decorator-wechat#5]
手机：google pixel2
Android Pie 12月5日
WeChat：6.7.3 play store 版
nevolution：2.3.2 play store 版
nevo-WeChat：1.7 play store 版

微信自己的消息不走系统的通知通道，我将自己手机开启免打扰模式后，微信新消息还是会有消息提示音，只是不在消息通知栏中显示。这导致我想开启免打扰模式安心工作的时候，经常被微信打扰，不得已只能使用震动模式或静音来代替。

使用了nevo-WeChat后，这个事情还是如此，微信消息声音在免打扰模式下依旧会响。我在想，是不是可以将微信自己的消息提示音改为静音，然后设置nevo-WeChat的消息提醒，然后，就可以实现“微信的消息也受到免打扰模式的管理”，但事实上，目前在应用管理-> nevo-WeChat -> 提醒设置中，并没有相关的关于提醒声音的设置。

所以，我希望，nevo-WeChat在接管微信通知栏消息的基础上，可以再接管一下它的提醒声音及设置。

**Comment by oasisfeng** [comment]
在进化后的微信消息上长按，进入通知类别设置，里面可以开启提示音。（先关闭微信设置中的通知提示音）
