### ISSUE TITLE
找不到sdk的1.2.0版本，build异常

### ISSUE THREAD

**Issue by tianzhijiexian** [Nevolution/decorator-wechat#6]
implementation 'com.oasisfeng.nevo:sdk:1.2.0'
上述的版本jcenter找不到，无法build

目前只有1.1.1的版本，url：http://jcenter.bintray.com/com/oasisfeng/nevo/sdk/

**Comment by oasisfeng** [comment]
抱歉，刚注意到 1.2.0 的 release 出了点问题，我会尽快重新发布。

**Comment by oasisfeng** [comment]
SDK v1.2.0 现已发布到 jcenter，请更新至最新代码后 build。

**Comment by tianzhijiexian** [comment]
最新代码可以了，感谢作者
