### ISSUE TITLE
增加进入微信后自动清除通知消息的功能

### ISSUE THREAD

**Issue by tianzhijiexian** [Nevolution/decorator-wechat#7]
机型：三星s10
系统：android p
适用的app：最新的master上的decorator-wechat代码

目前使用中遇到两个问题：
1.安装后发现来了消息后会有两次通知提示音
2.如果不是通过点击通知进入微信，那么直接从桌面进入微信的话通知栏消息会一直存在，必须手动清除

以上是一个个人使用中遇到的问题，这是一个极其优秀的项目，所以希望越做越好

**Comment by notxx** [comment]
既然是三星手机，我就先假定你没有root，也没给nevo做系统化。这个情况下nevo只能用外源模式，所以两个问题都是正常的。
1可以通过把微信自己的通知提示音关掉解决；
2要解决可能只能用无障碍服务，但是用了无障碍服务，尤其是用于这种和无障碍完全无关的目的，Google Play大概率会下架的。

**Comment by tianzhijiexian** [comment]
@notxx 感谢回复，看来没有什么别的好方案了。

**Comment by oasisfeng** [comment]
1. 一般可通过开启增强模式消除。如果仍然存在两次提示音，可能是开启了过多的通知侦听器（授予通知访问权的应用），影响了处理性能。
2. Nevolution 提供了同步移除通知的功能，只需要执行 ADB 指令，不需要 root。但目前的实现不够完善，在某些机型上会出现一段时间后失效。计划在未来版本中重写这个机制。

**Comment by tianzhijiexian** [comment]
@oasisfeng 感谢回复
