### ISSUE TITLE
微信在MIUI10最新版中无法弹出通知

### ISSUE THREAD

**Issue by raining1123** [Nevolution/decorator-wechat#8]
大神好！反映一个新bug，我是小米9升级到了MIUI10 9.4.1开发版，开启女娲石之后通知不再弹出。
这个版本MIUI貌似对通知系统进行了较大改动，好处是加入了官方自定义单独app通知声的设置，坏处就是影响到了女娲石。
具体来说，此前女娲石和微信插件以及快捷回复都正常，但是新系统下来消息时只有振动声音，通知没有弹出。经过对比，老系统里要去nevo的通知权限里把所有选项都打开，特别是“微信”栏目里的；但是新系统按照老办法居然找不到nevo的“微信”栏目。

![新系统设置](https://i.imgur.com/he0lKwt.png)
![老系统设置](https://i.imgur.com/DHyobsy.png)

**Comment by oasisfeng** [comment]
目前在 MIUI 10 9.2.x 上未能复现上述问题。机型适配问题，请抓取一份收到通知前后的 logcat，有助于分析。

**Comment by raining1123** [comment]
@oasisfeng 经过研究，发现在新系统里把女娲石这个组件识别为系统应用了，默认隐藏起来了。
好不容易找出来，开了通知权限就好了～
![](https://i.imgur.com/aW6wcqc.png)![](https://i.imgur.com/OkZAg2i.png)

**Comment by oasisfeng** [comment]
使用了 Magisk 模块？

**Comment by raining1123** [comment]
@oasisfeng 并没有啊，从来没装过magisk

**Comment by notxx** [comment]
第二张图下面第二个按钮是“卸载”而不是“卸载更新”，所以其实没有被系统化。不过miui中隐藏组件也不知道是什么规则，挺奇怪的。

@raining1123 还是装个magisk然后把nevo系统化吧，就可以开启内源模式了，好处多多

**Comment by oasisfeng** [comment]
@notxx 内源模式并不需要 Magisk 模块或把 Nevolution 系统化，只需要 root 即可。

**Comment by notxx** [comment]
@oasisfeng MIUI下仅仅root是不行的，还是会被系统阻止自启

**Comment by oasisfeng** [comment]
@notxx 可以在 MIUI 系统的应用设置中为其开启自启动，并关闭省电优化。
