### ISSUE TITLE
有關微信推送到GALAXY WATCH 的問題

### ISSUE THREAD

**Issue by nelsongm** [Nevolution/decorator-wechat#9]
https://jingyan.baidu.com/article/5553fa827afe7e65a239341d.htm
大神好，已經按照以上網站步驟設定手機，但無法推到手機上，可否提供一些教學協助，十分感謝
手機為：華為P30PRO
版本EMUI 9.1.0.140

**Comment by oasisfeng** [comment]
Galaxy Watch 并非 Wear OS (Android) 系统。由于这边缺少相应的设备，目前无法提供有效的协助，抱歉。
